name: India RSS Engine

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ✅ Python dependency install
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install feedparser

      # ✅ Fetch RSS data
      - name: Fetch RSS feeds
        run: |
          python3 << 'EOF'
          import feedparser, json

          feeds = [
            ("https://pib.gov.in/rssfeed.aspx","PIB"),
            ("https://rbi.org.in/Scripts/Rss.aspx","RBI"),
            ("https://prsindia.org/rss","PRS"),
            ("https://www.mospi.gov.in/rss","MOSPI"),
            ("https://eci.gov.in/rss/","ECI"),
            ("https://www.niti.gov.in/rss.xml","NITI"),
            ("https://mausam.imd.gov.in/rss/","IMD"),
            ("https://cpcb.nic.in/rss-feed/","CPCB"),
            ("https://www.un.org/india/rss.xml","UN"),
            ("https://www.worldbank.org/en/country/india/news?rss=true","WorldBank")
          ]

          data=[]
          for url,hub in feeds:
              feed = feedparser.parse(url)
              for entry in feed.entries[:2]:
                  data.append({
                      "hub": hub,
                      "title": entry.title,
                      "link": entry.link,
                      "date": entry.get("published","")
                  })

          with open("data.json","w",encoding="utf-8") as f:
              json.dump(data,f,indent=2,ensure_ascii=False)
          EOF

      # ✅ Commit result
      - name: Commit data
        run: |
          git config user.name "engine-bot"
          git config user.email "bot@engine.in"
          git add data.json
          git commit -m "auto update rss data" || echo "no changes"
          git push
